artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Puzan789/Datas/raw/refs/heads/main/translatordata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/textdata

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["eng.txt", "nep.txt"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/textdata
  tokenizer_file: artifacts/data_transformation/tokenizer_{0}.json
  src_file: artifacts/data_ingestion/textdata/eng.txt
  tgt_file: artifacts/data_ingestion/textdata/nep.txt

data_training:
  root_dir: artifacts/data_training
  model_path: artifacts/data_training/weights
  experiment_path: artifacts/data_training/runs/tmodel
  train_data_path: artifacts/data_transformation/train.txt
  preload: None
  model_basename: 'tmodel_'