artifacts: artifacts

data_ing:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Puzan789/Datas/blob/main/translatordata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
